
-- version 1.0
-- Oracle 19c

CREATE TABLE item_category (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_title VARCHAR(255) DEFAULT NULL
);


CREATE TABLE item (
   item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   serial_number VARCHAR(255) DEFAULT NULL,
   title VARCHAR(255) DEFAULT NULL,
   itemdescription VARCHAR(255) DEFAULT NULL,
   price DECIMAL(10,2) DEFAULT NULL,
   image_url VARCHAR(255) DEFAULT NULL,
   is_active NUMBER(1) DEFAULT 1,
   item_availability NUMBER(11) DEFAULT NULL,
   created_at DATE DEFAULT NULL,
   last_updated_at DATE DEFAULT NULL,
   category_id NUMBER NOT NULL,

  CONSTRAINT fk_category_id 
        FOREIGN KEY (category_id) 
        REFERENCES item_category ( category_id )
        ON DELETE CASCADE

); 




