
-- version 1.0
-- IBM DB2

CREATE TABLE item_category (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_title VARCHAR(255) DEFAULT NULL
);


CREATE TABLE item (
   item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   serial_number VARCHAR(255) DEFAULT NULL,
   title VARCHAR(255) DEFAULT NULL,
   item_description VARCHAR(255) DEFAULT NULL,
   price DECIMAL(10,2) DEFAULT NULL,
   image_url VARCHAR(255) DEFAULT NULL,
   is_active SMALLINT DEFAULT 1,
   item_availability SMALLINT DEFAULT NULL,
   created_at DATE DEFAULT NULL,
   last_updated_at DATE DEFAULT NULL,
   category_id SMALLINT NOT NULL,

  CONSTRAINT fk_category_id 
        FOREIGN KEY (category_id) 
        REFERENCES item_category ( category_id )
        ON DELETE CASCADE

); 




